-- 코드를 입력하세요
SELECT PRODUCT_CODE, p.PRICE * SUM(SALES_AMOUNT) as SALES
FROM PRODUCT p
# JOIN OFFLINE_SALE o ON p.PRODUCT_ID = o.PRODUCT_ID

# INNER JOIN 일 경우에만 USING 사용가능, OUTER JOIN은 AND 조건을 붙일 수 없다.
JOIN OFFLINE_SALE o USING(PRODUCT_ID)
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC