-- 코드를 입력하세요
# SELECT ins.NAME, ins.DATETIME
# FROM ANIMAL_INS ins
# LEFT JOIN ANIMAL_OUTS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID 
# WHERE outs.ANIMAL_ID IS NULL
# ORDER BY ins.DATETIME ASC
# LIMIT 0, 3;

SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
)
ORDER BY DATETIME ASC
LIMIT 3;